In [1]:
!pip install syft

     |████████████████████████████████| 286kB 1.8MB/s 
     |████████████████████████████████| 389kB 41.6MB/s 
     |████████████████████████████████| 204kB 40.9MB/s 
     |████████████████████████████████| 2.1MB 29.6MB/s 
     |████████████████████████████████| 81kB 26.2MB/s 
     |████████████████████████████████| 460kB 47.9MB/s 
     |████████████████████████████████| 256kB 44.6MB/s 
     |████████████████████████████████| 51kB 18.7MB/s 
     |████████████████████████████████| 266kB 48.8MB/s 
     |████████████████████████████████| 122kB 46.6MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067053 sha256=38636ac6a9ccda5a3d77f14cf4a84c1d78109a6c937b6a094388564a19dad592
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=c19477a3a14fefbb888de9a20c2becd1e621ad0c8fd262493fe3d42f260a0304
  Stored in di

In [77]:
import torch 
num_entries = 20
db = torch.rand(num_entries) > 0.5
db

tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
       dtype=torch.uint8)

In [0]:
remove_index=2

In [0]:
def get_parallel_db(db, remove_index):
  return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [80]:
get_parallel_db(db, 3)

tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
       dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [84]:
pdbs

[tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,

In [0]:
 def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries)>0.5
    pdb = get_parallel_dbs(db)
    
    return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [89]:
db

tensor([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       dtype=torch.uint8)

In [90]:
pdbs

[tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,