In [4]:
import torch #import pytorch

In [5]:
def activation(x):
    """
    Sigmoid activation fucntion
    Arguments
    ------
    x:torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [18]:
torch.manual_seed(42)
features=torch.randn((1,5))
weights=torch.randn_like(features)
bias=torch.randn((1,1))

In [16]:
weights.view(5,1)

tensor([[-0.1863],
        [ 2.2082],
        [-0.6380],
        [ 0.4617],
        [ 0.2674]])

In [38]:
print('#features',activation(features))
print('#weights',activation(weights))
print('#bias',activation(bias))

#features tensor([[0.5834, 0.5322, 0.5583, 0.5573, 0.2455]])
#weights tensor([[0.4536, 0.9010, 0.3457, 0.6134, 0.5664]])
#bias tensor([[0.6306]])


In [48]:
features.shape

torch.Size([1, 5])

In [52]:
features

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229]])

In [64]:
features.reshape(1,5)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229]])

In [74]:
features.resize_(5,1)

tensor([[ 0.3367],
        [ 0.1288],
        [ 0.2345],
        [ 0.2303],
        [-1.1229]])

In [66]:
features.view(1,5)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229]])

In [71]:
features.view(5,1)

tensor([[ 0.3367],
        [ 0.1288],
        [ 0.2345],
        [ 0.2303],
        [-1.1229]])

In [75]:
torch.mm(features,weights)

tensor([[-0.0627,  0.7435, -0.2148,  0.1554,  0.0900],
        [-0.0240,  0.2844, -0.0822,  0.0595,  0.0344],
        [-0.0437,  0.5177, -0.1496,  0.1082,  0.0627],
        [-0.0429,  0.5086, -0.1470,  0.1063,  0.0616],
        [ 0.2092, -2.4795,  0.7164, -0.5184, -0.3002]])

In [108]:
y=activation(torch.mm(features*weights)+bias)
y

tensor([[0.6018]])

In [111]:
y=activation(torch.mm(features,weights.view(5,1))+bias)
y

tensor([[0.6018]])

In [117]:
torch.manual_seed(7) #random seed
features=torch.randn((1,3))

#defining the size of each layer
n_input= features.shape[1]
n_hidden=2
n_output=1

#weights for inputs to hidden layer
w1=torch.randn(n_input, n_hiden) #3x2

#weigths for hidden layer to  output layer
w2= torch.randn(n_hidden, n_output) #2x1

#and bias terms for hidden and output laeyers
B1=torch.randn((1,n_hidden)) #1x2
B2=torch.randn((1,n_output)) #1x1

In [118]:
w1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [119]:
w2

tensor([[-1.6822],
        [ 0.3177]])

In [120]:
print(B1)

tensor([[0.1328, 0.1373]])


In [121]:
print(B2)

tensor([[0.2405]])


In [122]:
r1= activation(torch.mm(features,w1)+B1)
r2= activation(torch.mm(r1,w2)+B2)
r2

tensor([[0.3171]])

In [93]:
import numpy as np
a=np.random.rand(4,3)
a

array([[0.36241618, 0.20229877, 0.1747358 ],
       [0.88208354, 0.02479612, 0.15832703],
       [0.08052354, 0.09490016, 0.78738332],
       [0.63890031, 0.04712906, 0.67072698]])

In [94]:
b=torch.from_numpy(a)
b

tensor([[0.3624, 0.2023, 0.1747],
        [0.8821, 0.0248, 0.1583],
        [0.0805, 0.0949, 0.7874],
        [0.6389, 0.0471, 0.6707]], dtype=torch.float64)

In [95]:
b.numpy()

array([[0.36241618, 0.20229877, 0.1747358 ],
       [0.88208354, 0.02479612, 0.15832703],
       [0.08052354, 0.09490016, 0.78738332],
       [0.63890031, 0.04712906, 0.67072698]])

In [97]:
b.mul_(2)

tensor([[0.7248, 0.4046, 0.3495],
        [1.7642, 0.0496, 0.3167],
        [0.1610, 0.1898, 1.5748],
        [1.2778, 0.0943, 1.3415]], dtype=torch.float64)

In [98]:
a

array([[0.72483236, 0.40459754, 0.3494716 ],
       [1.76416707, 0.04959223, 0.31665405],
       [0.16104709, 0.18980033, 1.57476664],
       [1.27780063, 0.09425812, 1.34145397]])